<?php

namespace PacienteBundle\Repository;

/**
 * borarrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class borarrRepository extends \Doctrine\ORM\EntityRepository
{
}
